In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
torch.__version__

'2.1.0+cu121'

In [2]:
!nvidia-smi

Tue Jan 30 01:30:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
# tensor
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item() # get tensor back as python int

7

In [6]:
vector = torch.tensor([7,7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [7]:
# matrix
matrix = torch.tensor([[4,5],
                      [2,3]])
matrix, matrix.ndim, matrix.shape

(tensor([[4, 5],
         [2, 3]]),
 2,
 torch.Size([2, 2]))

In [8]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor, tensor.ndim, tensor.shape

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]),
 3,
 torch.Size([1, 3, 3]))

In [9]:
# Random tensor
random_tensor = torch.rand(3,4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.7543, 0.9546, 0.4079, 0.5058],
         [0.1263, 0.1888, 0.6145, 0.2707],
         [0.7385, 0.8172, 0.3607, 0.2974]]),
 2,
 torch.Size([3, 4]))

In [10]:
rand_img_size = torch.rand(size=(3,224,224))
rand_img_size.ndim, rand_img_size.shape, rand_img_size.dtype

(3, torch.Size([3, 224, 224]), torch.float32)

In [11]:
## Zeros and onces
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros, ones, ones.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [12]:
# RANGE - arange tensor
one_to_10 = torch.arange(start=1, end=11, step=1)
one_to_10

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
ten_zeros = torch.zeros_like(input=one_to_10)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
float_32_tensor = torch.tensor([3.0,2.0,9.0],
                               dtype=None, # what dtype
                               device=None, # what device is yr tensor is on - cpu or cuda(gpu)
                               requires_grad=False) # whether or not track gradients with this tensors operations
float_32_tensor, float_32_tensor.dtype

(tensor([3., 2., 9.]), torch.float32)

In [15]:
f_16 = float_32_tensor.type(torch.float16)
f_16

tensor([3., 2., 9.], dtype=torch.float16)

In [16]:
f_16 * float_32_tensor

tensor([ 9.,  4., 81.])

In [17]:
## getting info from tensors
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4914, 0.7457, 0.1448, 0.1200],
        [0.5160, 0.9259, 0.7337, 0.6027],
        [0.3769, 0.3685, 0.2969, 0.0659]])

In [18]:
some_tensor, some_tensor.shape, some_tensor.dtype, some_tensor.size(), some_tensor.device

(tensor([[0.4914, 0.7457, 0.1448, 0.1200],
         [0.5160, 0.9259, 0.7337, 0.6027],
         [0.3769, 0.3685, 0.2969, 0.0659]]),
 torch.Size([3, 4]),
 torch.float32,
 torch.Size([3, 4]),
 device(type='cpu'))

In [19]:
#some_tensor.to("cuda")

In [20]:
tensor = torch.tensor([11,2,3])
tensor + 10, tensor

(tensor([21, 12, 13]), tensor([11,  2,  3]))

In [21]:
torch.max(tensor)

tensor(11)

In [22]:
# element vise mult vs Matrix mult
tensor.mul(tensor), tensor.matmul(tensor)

(tensor([121,   4,   9]), tensor(134))

In [23]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 324 µs, sys: 0 ns, total: 324 µs
Wall time: 442 µs


tensor(134)

In [24]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 46 µs, sys: 8 µs, total: 54 µs
Wall time: 57 µs


tensor(134)

In [25]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32) # 3x2

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32) # 3x2 change to 2x3

# torch.matmul(tensor_A, tensor_B) # (this will error)
# to solve it transform a or b
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [26]:
torch.reshape(tensor_B, shape=(2,3)), tensor_B.T
# transform and reshape gives different output
# generally transpose it better option

(tensor([[ 7., 10.,  8.],
         [11.,  9., 12.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [27]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [29]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [30]:
# torch mean fun requires float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [31]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [32]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [33]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [34]:
x=torch.arange(1.0,10.0)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
torch.reshape(x, shape=(3,3)), torch.reshape(x, shape=(1,3,3))

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]))

In [36]:
torch.reshape(x, shape=(3,1,3)), torch.reshape(x, shape=(3,3,1))

(tensor([[[1., 2., 3.]],
 
         [[4., 5., 6.]],
 
         [[7., 8., 9.]]]),
 tensor([[[1.],
          [2.],
          [3.]],
 
         [[4.],
          [5.],
          [6.]],
 
         [[7.],
          [8.],
          [9.]]]))

In [37]:
# change view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [38]:
# changing z changes x because they share same memory
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [39]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [40]:
torch.vstack([x,x,x,x]), torch.stack([x,x,x,x], dim=0)

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [41]:
torch.hstack([x,x,x,x])

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [42]:
x = torch.unsqueeze(x, dim=1)
x, x.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [43]:
x.squeeze().shape

torch.Size([9])

In [44]:
# permute rearrange the tensor
x_original = torch.rand(size=(224,224,3))

# permute the original tensor to rearrange the axis/dim
x_permuted = x_original.permute(2,0,1) # 2nd dim, 0thdim, 1st dim = 3,224,224

In [45]:
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [46]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [47]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [49]:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [50]:
x[0, 2,2], x[0][2][2]

(tensor(9), tensor(9))

In [51]:
# numpy to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # when converting from np dtype will f64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [52]:
torch.arange(1.0,8.0).dtype # normally default type if f32

torch.float32

In [53]:
# tensor to numpt
tensor = torch.ones(7)
num_tensor = tensor.numpy()
tensor, num_tensor, num_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [54]:
tensor = tensor + 1
tensor, num_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [55]:
torch.rand(3,3)

tensor([[0.4662, 0.9317, 0.8084],
        [0.4285, 0.8704, 0.9148],
        [0.4799, 0.1273, 0.0327]])

In [56]:
# to reduce randomness we can use 'seed'- 'seed' adds flavour in randomness
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

random_tensor_a, random_tensor_b, random_tensor_a==random_tensor_b

(tensor([[0.9518, 0.7629, 0.8385, 0.1845],
         [0.6714, 0.9631, 0.8005, 0.2882],
         [0.4364, 0.3477, 0.9027, 0.4481]]),
 tensor([[0.1691, 0.0653, 0.3820, 0.7313],
         [0.5847, 0.1544, 0.3216, 0.8537],
         [0.8942, 0.2951, 0.3000, 0.4856]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [57]:
# reproducable seed
# manual seed is work for only one code line

Random_seed = 42

torch.manual_seed(Random_seed) # attaching seed to random ness to get same output
random_tensor_c = torch.rand(3,4)

torch.manual_seed(Random_seed) # attaching seed to random ness to get same output
random_tensor_d = torch.rand(3,4)

random_tensor_c, random_tensor_d, random_tensor_c==random_tensor_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [58]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
device

'cuda'

In [59]:
!nvidia-smi

Tue Jan 30 01:43:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--